var questions=[
    {q: "What is JavaScript?",
    a1: "Creates interaction within webpage",
    a2: "Describes the structure of the webpage",
    a3: "Describes how HTML elements will be displayed on screen",
    a4: "Browser creates DOM constructed as tree of objects",
    correct: "Creates interaction within webpage"},
    {q: "Which tag do you use to add external JavaScript file in HTML?",
    a1: "<link>",
    a2: "<script>",
    a3: "<a href=>",
    a4: "<JavaScript>",
    correct: "<script>"},
    {q: "If B=10 and C=\"10\" which of the following returns true?",
    a1: "b<c",
    a2: "b!==c",
    a3: "b>=c",
    a4: "b==c",
    correct: "b==c"},
    {q: "Which number in the array is logged by console.log(numbers[3])? \n var numbers=[4,9,12,5,2,1]",
    a1: "9",
    a2: "12",
    a3: "2",
    a4: "5",
    correct: "5"},
    {q: "Which of the following is false about prevent default?",
    a1: "If there is a default action that belongs to event it will not occur",
    a2: "In function use event.preventDefault()",
    a3: "If prevent default added to checkbox event listener the box wont be checked when clicked",
    a4: "Only calling prevent default at the start of an event cancels the event",
    correct:"Only calling prevent default at the start of an event cancels the event"},
    {q: "How would you end an element to the end of an array called names?",
    a1: "names.push",
    a2: "names.pop",
    a3: "names.sort",
    a4: "names.splice",
    correct: "names.push"},  
    {q: "Which event has the correct explanation?",
    a1: "keydown: event fires when key on keyboard is released",
    a2: "click: event fires when spacebar is pressed",
    a3: "mousedown: event fires when mouse is pressed",
    a4: "scroll: event fires when element has been scrolled",
    correct: "scroll: event fires when element has been scrolled"}, 
     {q: "What is the difference between setInterval and setTimeout?",
    a1: "setTimeout allows function to run repeatedly and setInterval allows function to run once after interval of time",
    a2: "setTimeout creates a timer and setInterval sets amount of time it runs",
    a3: "setInterval creates a timer function and setTimeout stops execution of timer function",
    a4: "setInterval allows function to run repeatedly and setTimeout allows function to run once after interval of time",
    correct:"setInterval allows function to run repeatedly and setTimeout allows function to run once after set interval of time"},  
    {q: "Which of the following converts a JSON string into JSON object?",
    a1: "JSON.parse()",
    a2: "JSON.object()",
    a3: "JSON.convert()",
    a4: "JSON.stringify()",
    correct: "JSON.parse()"},  
    {q: "What would you use to repeat a specifc block of code a known number of times?",
    a1: "conditional statement",
    a2: "for loop",
    a3: "while loop",
    a4: "array",
    correct: "for loop"},
]
